services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=exambyte"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=pass"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist the database data across restarts

volumes:
  postgres-data: